const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.wrap,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Dictionary,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Dictionary.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Dictionary.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{sky: 0},
	{Title: 0},
	{wave_base: 0},
	{Wrap: 0},
	{wave: 0},
	{sand: 0},
	{clouds: 0},
	{seal: 0},
	{shark: 0},
	{play: 0},
	{shop: 0},
	{Mouse: 0},
	{Touch: 0},
	{cloud: 0},
	{random_did_you_know: 0},
	{loading_screen_fact: 0},
	{price: 0},
	{shop_beachball: 0},
	{shop_shell: 0},
	{shop_starfish: 0},
	{shop_chair: 0},
	{shop_sandcastle: 0},
	{name_beachball: 0},
	{remaincoins: 0},
	{coins: 0},
	{price_beachball: 0},
	{buy_beachball: 0},
	{remain_coins: 0},
	{coins_beachball: 0},
	{name_shell: 0},
	{name_starfish: 0},
	{name_chair: 0},
	{name_sandcastle: 0},
	{coins_shell: 0},
	{coins_starfish: 0},
	{coins_chair: 0},
	{coins_sandcastle: 0},
	{price_shell: 0},
	{price_starfish: 0},
	{price_chair: 0},
	{price_sandcastle: 0},
	{buy_shell: 0},
	{buy_starfish: 0},
	{buy_chair: 0},
	{buy_sandcastle: 0},
	{shop_umbrella: 0},
	{shop_sunglasses: 0},
	{name_umbrella: 0},
	{name_sunglasses: 0},
	{coins_umbrella: 0},
	{coins_sunglasses: 0},
	{price_umbrella: 0},
	{price_sunglasses: 0},
	{buy_umbrella: 0},
	{buy_sunglasses: 0},
	{shop_coconut: 0},
	{shop_sandbucket: 0},
	{shop_hat: 0},
	{shop_sandals: 0},
	{shop_floatie: 0},
	{shop_turtle: 0},
	{shop_shovel: 0},
	{name_coconut: 0},
	{name_sandbucket: 0},
	{name_hat: 0},
	{name_sandals: 0},
	{name_floatie: 0},
	{name_turtle: 0},
	{name_shovel: 0},
	{coins_coconut: 0},
	{coins_sandbucket: 0},
	{coins_hat: 0},
	{coins_sandals: 0},
	{coins_floatie: 0},
	{coins_turtle: 0},
	{coins_shovel: 0},
	{price_coconut: 0},
	{price_sandbucket: 0},
	{price_hat: 0},
	{price_sandals: 0},
	{price_floatie: 0},
	{price_turtle: 0},
	{price_shovel: 0},
	{buy_coconut: 0},
	{buy_sandbucket: 0},
	{buy_hat: 0},
	{buy_sandals: 0},
	{buy_floatie: 0},
	{buy_turtle: 0},
	{buy_shovel: 0},
	{speech_bubble: 0},
	{play_count: 0},
	{speech_bubble_text: 0},
	{DragDrop: 0},
	{apple_juice: 0},
	{milk_carton: 0},
	{words_center: 0},
	{Collections_Beach: 0},
	{visitgarden: 0},
	{beachball: 0},
	{shell: 0},
	{starfish: 0},
	{chair: 0},
	{sandcastle: 0},
	{umbrella: 0},
	{sunglasses: 0},
	{coconut: 0},
	{sandbucket: 0},
	{hat: 0},
	{sandals: 0},
	{floatie: 0},
	{turtle: 0},
	{shovel: 0},
	{items_bought: 0},
	{bought_beachball: 0},
	{bought_shell: 0},
	{bought_starfish: 0},
	{bought_chair: 0},
	{bought_sandcastle: 0},
	{bought_umbrella: 0},
	{bought_sunglasses: 0},
	{menu_button: 0},
	{trash_can: 0},
	{recycle_bin: 0},
	{bought_coconut: 0},
	{bought_sandbucket: 0},
	{bought_hat: 0},
	{bought_sandals: 0},
	{bought_floatie: 0},
	{bought_turtle: 0},
	{bought_shovel: 0},
	{compost_bin: 0},
	{banana_peel: 0},
	{apple_core: 0},
	{pizza_box: 0},
	{bottle_caps: 0},
	{yogurt_pack: 0},
	{chips: 0},
	{help_button: 0},
	{build_progress: 0},
	{shop_items: 0},
	{trash_items: 0},
	{bins: 0},
	{compost_trash: 0},
	{recycle_trash: 0},
	{trash_trash: 0}
];

self.InstanceType = {
	sky: class extends self.ITiledBackgroundInstance {},
	Title: class extends self.ISpriteInstance {},
	wave_base: class extends self.ISpriteInstance {},
	wave: class extends self.ISpriteInstance {},
	sand: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	seal: class extends self.ISpriteInstance {},
	shark: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	shop: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	cloud: class extends self.ISpriteInstance {},
	loading_screen_fact: class extends self.ITextInstance {},
	shop_beachball: class extends self.ISpriteInstance {},
	shop_shell: class extends self.ISpriteInstance {},
	shop_starfish: class extends self.ISpriteInstance {},
	shop_chair: class extends self.ISpriteInstance {},
	shop_sandcastle: class extends self.ISpriteInstance {},
	name_beachball: class extends self.ITextInstance {},
	coins: class extends self.ISpriteInstance {},
	price_beachball: class extends self.ITextInstance {},
	buy_beachball: class extends self.IButtonInstance {},
	remain_coins: class extends self.ITextInstance {},
	coins_beachball: class extends self.ISpriteInstance {},
	name_shell: class extends self.ITextInstance {},
	name_starfish: class extends self.ITextInstance {},
	name_chair: class extends self.ITextInstance {},
	name_sandcastle: class extends self.ITextInstance {},
	coins_shell: class extends self.ISpriteInstance {},
	coins_starfish: class extends self.ISpriteInstance {},
	coins_chair: class extends self.ISpriteInstance {},
	coins_sandcastle: class extends self.ISpriteInstance {},
	price_shell: class extends self.ITextInstance {},
	price_starfish: class extends self.ITextInstance {},
	price_chair: class extends self.ITextInstance {},
	price_sandcastle: class extends self.ITextInstance {},
	buy_shell: class extends self.IButtonInstance {},
	buy_starfish: class extends self.IButtonInstance {},
	buy_chair: class extends self.IButtonInstance {},
	buy_sandcastle: class extends self.IButtonInstance {},
	shop_umbrella: class extends self.ISpriteInstance {},
	shop_sunglasses: class extends self.ISpriteInstance {},
	name_umbrella: class extends self.ITextInstance {},
	name_sunglasses: class extends self.ITextInstance {},
	coins_umbrella: class extends self.ISpriteInstance {},
	coins_sunglasses: class extends self.ISpriteInstance {},
	price_umbrella: class extends self.ITextInstance {},
	price_sunglasses: class extends self.ITextInstance {},
	buy_umbrella: class extends self.IButtonInstance {},
	buy_sunglasses: class extends self.IButtonInstance {},
	shop_coconut: class extends self.ISpriteInstance {},
	shop_sandbucket: class extends self.ISpriteInstance {},
	shop_hat: class extends self.ISpriteInstance {},
	shop_sandals: class extends self.ISpriteInstance {},
	shop_floatie: class extends self.ISpriteInstance {},
	shop_turtle: class extends self.ISpriteInstance {},
	shop_shovel: class extends self.ISpriteInstance {},
	name_coconut: class extends self.ITextInstance {},
	name_sandbucket: class extends self.ITextInstance {},
	name_hat: class extends self.ITextInstance {},
	name_sandals: class extends self.ITextInstance {},
	name_floatie: class extends self.ITextInstance {},
	name_turtle: class extends self.ITextInstance {},
	name_shovel: class extends self.ITextInstance {},
	coins_coconut: class extends self.ISpriteInstance {},
	coins_sandbucket: class extends self.ISpriteInstance {},
	coins_hat: class extends self.ISpriteInstance {},
	coins_sandals: class extends self.ISpriteInstance {},
	coins_floatie: class extends self.ISpriteInstance {},
	coins_turtle: class extends self.ISpriteInstance {},
	coins_shovel: class extends self.ISpriteInstance {},
	price_coconut: class extends self.ITextInstance {},
	price_sandbucket: class extends self.ITextInstance {},
	price_hat: class extends self.ITextInstance {},
	price_sandals: class extends self.ITextInstance {},
	price_floatie: class extends self.ITextInstance {},
	price_turtle: class extends self.ITextInstance {},
	price_shovel: class extends self.ITextInstance {},
	buy_coconut: class extends self.IButtonInstance {},
	buy_sandbucket: class extends self.IButtonInstance {},
	buy_hat: class extends self.IButtonInstance {},
	buy_sandals: class extends self.IButtonInstance {},
	buy_floatie: class extends self.IButtonInstance {},
	buy_turtle: class extends self.IButtonInstance {},
	buy_shovel: class extends self.IButtonInstance {},
	speech_bubble: class extends self.ISpriteInstance {},
	speech_bubble_text: class extends self.ITextInstance {},
	apple_juice: class extends self.ISpriteInstance {},
	milk_carton: class extends self.ISpriteInstance {},
	words_center: class extends self.ITextInstance {},
	Collections_Beach: class extends self.ISpriteInstance {},
	visitgarden: class extends self.ISpriteInstance {},
	items_bought: class extends self.IDictionaryInstance {},
	bought_beachball: class extends self.ISpriteInstance {},
	bought_shell: class extends self.ISpriteInstance {},
	bought_starfish: class extends self.ISpriteInstance {},
	bought_chair: class extends self.ISpriteInstance {},
	bought_sandcastle: class extends self.ISpriteInstance {},
	bought_umbrella: class extends self.ISpriteInstance {},
	bought_sunglasses: class extends self.ISpriteInstance {},
	menu_button: class extends self.ISpriteInstance {},
	trash_can: class extends self.ISpriteInstance {},
	recycle_bin: class extends self.ISpriteInstance {},
	bought_coconut: class extends self.ISpriteInstance {},
	bought_sandbucket: class extends self.ISpriteInstance {},
	bought_hat: class extends self.ISpriteInstance {},
	bought_sandals: class extends self.ISpriteInstance {},
	bought_floatie: class extends self.ISpriteInstance {},
	bought_turtle: class extends self.ISpriteInstance {},
	bought_shovel: class extends self.ISpriteInstance {},
	compost_bin: class extends self.ISpriteInstance {},
	banana_peel: class extends self.ISpriteInstance {},
	apple_core: class extends self.ISpriteInstance {},
	pizza_box: class extends self.ISpriteInstance {},
	bottle_caps: class extends self.ISpriteInstance {},
	yogurt_pack: class extends self.ISpriteInstance {},
	chips: class extends self.ISpriteInstance {},
	help_button: class extends self.IButtonInstance {},
	build_progress: class extends self.ITextInstance {},
	shop_items: class extends self.ISpriteInstance {},
	trash_items: class extends self.ISpriteInstance {},
	bins: class extends self.ISpriteInstance {},
	compost_trash: class extends self.ISpriteInstance {},
	recycle_trash: class extends self.ISpriteInstance {},
	trash_trash: class extends self.ISpriteInstance {}
}