const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.wrap,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Persist,
		C3.Plugins.Dictionary,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Dictionary.Acts.SetBoolInstanceVar,
		C3.Plugins.Dictionary.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.IsTouchingObject
	];
};
self.C3_JsPropNameTable = [
	{sky: 0},
	{Title: 0},
	{sand: 0},
	{Wrap: 0},
	{clouds: 0},
	{seal: 0},
	{play: 0},
	{shop: 0},
	{Mouse: 0},
	{Touch: 0},
	{cloud: 0},
	{random_did_you_know: 0},
	{loading_screen_fact: 0},
	{price: 0},
	{DragDrop: 0},
	{Persist: 0},
	{shop_beachball: 0},
	{shop_shell: 0},
	{shop_starfish: 0},
	{shop_chair: 0},
	{shop_sandcastle: 0},
	{item_names: 0},
	{remaincoins: 0},
	{where_to_go: 0},
	{coins: 0},
	{item_prices: 0},
	{remain_coins: 0},
	{item_coins: 0},
	{shop_umbrella: 0},
	{shop_sunglasses: 0},
	{shop_coconut: 0},
	{shop_sandbucket: 0},
	{shop_hat: 0},
	{shop_sandals: 0},
	{shop_floatie: 0},
	{shop_turtle: 0},
	{shop_shovel: 0},
	{speech_bubble: 0},
	{play_count: 0},
	{delay: 0},
	{speech_bubble_text: 0},
	{apple_juice: 0},
	{milk_carton: 0},
	{words_center: 0},
	{Collections_Beach: 0},
	{visitgarden: 0},
	{beachball: 0},
	{shell: 0},
	{starfish: 0},
	{chair: 0},
	{sandcastle: 0},
	{umbrella: 0},
	{sunglasses: 0},
	{coconut: 0},
	{sandbucket: 0},
	{hat: 0},
	{sandals: 0},
	{floatie: 0},
	{turtle: 0},
	{shovel: 0},
	{items_bought: 0},
	{menu_button: 0},
	{trash_can: 0},
	{recycle_bin: 0},
	{compost_bin: 0},
	{banana_peel: 0},
	{apple_core: 0},
	{pizza_box: 0},
	{bottle_caps: 0},
	{yogurt_pack: 0},
	{chips: 0},
	{shop_text: 0},
	{buybeachball: 0},
	{soldbeachball: 0},
	{buyshell: 0},
	{soldshell: 0},
	{buystarfish: 0},
	{buychair: 0},
	{buysandcastle: 0},
	{buyumbrella: 0},
	{buysunglasses: 0},
	{soldstarfish: 0},
	{soldchair: 0},
	{soldsandcastle: 0},
	{soldsunglasses: 0},
	{soldumbrella: 0},
	{buycoconut: 0},
	{soldcoconut: 0},
	{buysandbucket: 0},
	{buyhat: 0},
	{buysandals: 0},
	{buyfloatie: 0},
	{buyturtle: 0},
	{buyshovel: 0},
	{soldsandbucket: 0},
	{soldhat: 0},
	{soldsandals: 0},
	{soldfloatie: 0},
	{soldturtle: 0},
	{soldshovel: 0},
	{Sine: 0},
	{wave: 0},
	{help_click: 0},
	{help: 0},
	{audio: 0},
	{rectangle_background: 0},
	{examples: 0},
	{describe_help: 0},
	{help_icons: 0},
	{help_screen: 0},
	{help_title: 0},
	{left_arrow: 0},
	{right_arrow: 0},
	{exit_button: 0},
	{shop_items: 0},
	{trash_items: 0},
	{bins: 0},
	{compost_trash: 0},
	{recycle_trash: 0},
	{trash_trash: 0},
	{sold_buttons: 0}
];

self.InstanceType = {
	sky: class extends self.ITiledBackgroundInstance {},
	Title: class extends self.ISpriteInstance {},
	sand: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	seal: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	shop: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	cloud: class extends self.ISpriteInstance {},
	loading_screen_fact: class extends self.ITextInstance {},
	shop_beachball: class extends self.ISpriteInstance {},
	shop_shell: class extends self.ISpriteInstance {},
	shop_starfish: class extends self.ISpriteInstance {},
	shop_chair: class extends self.ISpriteInstance {},
	shop_sandcastle: class extends self.ISpriteInstance {},
	item_names: class extends self.ITextInstance {},
	coins: class extends self.ISpriteInstance {},
	item_prices: class extends self.ITextInstance {},
	remain_coins: class extends self.ITextInstance {},
	item_coins: class extends self.ISpriteInstance {},
	shop_umbrella: class extends self.ISpriteInstance {},
	shop_sunglasses: class extends self.ISpriteInstance {},
	shop_coconut: class extends self.ISpriteInstance {},
	shop_sandbucket: class extends self.ISpriteInstance {},
	shop_hat: class extends self.ISpriteInstance {},
	shop_sandals: class extends self.ISpriteInstance {},
	shop_floatie: class extends self.ISpriteInstance {},
	shop_turtle: class extends self.ISpriteInstance {},
	shop_shovel: class extends self.ISpriteInstance {},
	speech_bubble: class extends self.ISpriteInstance {},
	speech_bubble_text: class extends self.ITextInstance {},
	apple_juice: class extends self.ISpriteInstance {},
	milk_carton: class extends self.ISpriteInstance {},
	words_center: class extends self.ITextInstance {},
	Collections_Beach: class extends self.ISpriteInstance {},
	visitgarden: class extends self.ISpriteInstance {},
	items_bought: class extends self.IDictionaryInstance {},
	menu_button: class extends self.ISpriteInstance {},
	trash_can: class extends self.ISpriteInstance {},
	recycle_bin: class extends self.ISpriteInstance {},
	compost_bin: class extends self.ISpriteInstance {},
	banana_peel: class extends self.ISpriteInstance {},
	apple_core: class extends self.ISpriteInstance {},
	pizza_box: class extends self.ISpriteInstance {},
	bottle_caps: class extends self.ISpriteInstance {},
	yogurt_pack: class extends self.ISpriteInstance {},
	chips: class extends self.ISpriteInstance {},
	shop_text: class extends self.ITextInstance {},
	buybeachball: class extends self.ISpriteInstance {},
	soldbeachball: class extends self.ISpriteInstance {},
	buyshell: class extends self.ISpriteInstance {},
	soldshell: class extends self.ISpriteInstance {},
	buystarfish: class extends self.ISpriteInstance {},
	buychair: class extends self.ISpriteInstance {},
	buysandcastle: class extends self.ISpriteInstance {},
	buyumbrella: class extends self.ISpriteInstance {},
	buysunglasses: class extends self.ISpriteInstance {},
	soldstarfish: class extends self.ISpriteInstance {},
	soldchair: class extends self.ISpriteInstance {},
	soldsandcastle: class extends self.ISpriteInstance {},
	soldsunglasses: class extends self.ISpriteInstance {},
	soldumbrella: class extends self.ISpriteInstance {},
	buycoconut: class extends self.ISpriteInstance {},
	soldcoconut: class extends self.ISpriteInstance {},
	buysandbucket: class extends self.ISpriteInstance {},
	buyhat: class extends self.ISpriteInstance {},
	buysandals: class extends self.ISpriteInstance {},
	buyfloatie: class extends self.ISpriteInstance {},
	buyturtle: class extends self.ISpriteInstance {},
	buyshovel: class extends self.ISpriteInstance {},
	soldsandbucket: class extends self.ISpriteInstance {},
	soldhat: class extends self.ISpriteInstance {},
	soldsandals: class extends self.ISpriteInstance {},
	soldfloatie: class extends self.ISpriteInstance {},
	soldturtle: class extends self.ISpriteInstance {},
	soldshovel: class extends self.ISpriteInstance {},
	wave: class extends self.ISpriteInstance {},
	help: class extends self.ISpriteInstance {},
	audio: class extends self.IInstance {},
	rectangle_background: class extends self.ISpriteInstance {},
	examples: class extends self.ISpriteInstance {},
	describe_help: class extends self.ITextInstance {},
	help_icons: class extends self.ISpriteInstance {},
	help_title: class extends self.ITextInstance {},
	left_arrow: class extends self.ISpriteInstance {},
	right_arrow: class extends self.ISpriteInstance {},
	exit_button: class extends self.ISpriteInstance {},
	shop_items: class extends self.ISpriteInstance {},
	trash_items: class extends self.ISpriteInstance {},
	bins: class extends self.ISpriteInstance {},
	compost_trash: class extends self.ISpriteInstance {},
	recycle_trash: class extends self.ISpriteInstance {},
	trash_trash: class extends self.ISpriteInstance {},
	sold_buttons: class extends self.ISpriteInstance {}
}